name: PHPStan

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:f183ddf0e4179ab419b713fa5799dd9c3ee4481f5080ec786039bacc3a4be7f4
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPStan
        uses: docker://ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:f183ddf0e4179ab419b713fa5799dd9c3ee4481f5080ec786039bacc3a4be7f4
        with:
          args: analyze --error-format=table /github/workspace
